name: envname

on:
  workflow_dispatch:
    inputs:
      envName:
env:
  myenv: staging
      
      
jobs:
  deploy:
    runs-on: ubuntu-latest
  
    environment:
      name: ${{ github.event.inputs.envName }}
      
    steps:
    - run: echo "Deploy!"
#   build:
#     runs-on: ubuntu-latest
#     environment: 
#       name: ${{ env.myenv }}
#     steps:
#       - run: echo "Hi there"
